import os
import sys
import argparse
import json
from dotenv import load_dotenv

# Import parsers
from tools.pdf_parser import extract_text_from_pdf
from tools.docx_parser import extract_text_from_docx

# Import crew runner
from crew import run_resume_review_crew

def load_file_content(path: str) -> str:
    """
    Utility to load text from pdf, docx, or txt files.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"File not found: {path}")
        
    ext = os.path.splitext(path)[1].lower()
    if ext == ".pdf":
        return extract_text_from_pdf(path)
    elif ext == ".docx":
        return extract_text_from_docx(path)
    elif ext == ".txt" or ext == ".md":
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    else:
        raise ValueError(f"Unsupported file format: {ext}. Only PDF, DOCX, TXT, or MD are supported.")

def main():
    load_dotenv()
    
    parser = argparse.ArgumentParser(description="AI Resume Review Agent CLI using CrewAI")
    parser.add_argument("--resume", required=True, help="Path to resume file (PDF or DOCX)")
    parser.add_argument("--jd", required=True, help="Path to Job Description file (TXT, MD, PDF, or DOCX)")
    parser.add_argument("--model", default="gemini/gemini-2.5-flash", help="LLM model to use (default: gemini/gemini-2.5-flash)")
    parser.add_argument("--output", default="review_output.json", help="Path to save the JSON output")
    
    args = parser.parse_args()
    
    # 1. Fetch API key (Gemini first, then OpenAI fallback)
    api_key = os.getenv("GEMINI_API_KEY") or os.getenv("OPENAI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY (or OPENAI_API_KEY) environment variable is not set. Please set it in a .env file.")
        sys.exit(1)
        
    # 2. Extract text from inputs
    print("Reading and parsing input files...")
    try:
        resume_text = load_file_content(args.resume)
        print(f"Extracted {len(resume_text)} characters from resume.")
    except Exception as e:
        print(f"Failed to read resume file: {e}")
        sys.exit(1)
        
    try:
        jd_text = load_file_content(args.jd)
        print(f"Extracted {len(jd_text)} characters from job description.")
    except Exception as e:
        print(f"Failed to read job description file: {e}")
        sys.exit(1)
        
    # 3. Run Crew
    print(f"Running CrewAI with model: {args.model}...")
    try:
        results = run_resume_review_crew(
            resume_text=resume_text,
            job_description=jd_text,
            api_key=api_key,
            model_name=args.model
        )
        
        print("\n" + "="*50)
        print("          EXECUTIVE RESUME REVIEW REPORT")
        print("="*50)
        
        # Format and display Final Report
        report = results.get("final_report")
        if report:
            if hasattr(report, "executive_summary"):
                print(f"\nReadiness Rating: {report.hiring_readiness_rating.upper()}")
                print(f"ATS Score:        {report.ats_score}/100")
                print(f"Job Match Score:  {report.job_match_score}/100")
                print("\nExecutive Summary:")
                print(report.executive_summary)
                print("\nTop Improvements Required:")
                for i, imp in enumerate(report.top_improvements, 1):
                    print(f"  {i}. {imp}")
            else:
                # If parsed as dictionary
                print(f"\nReadiness Rating: {report.get('hiring_readiness_rating', 'N/A')}")
                print(f"ATS Score:        {report.get('ats_score', 'N/A')}/100")
                print(f"Job Match Score:  {report.get('job_match_score', 'N/A')}/100")
                print("\nExecutive Summary:")
                print(report.get('executive_summary', ''))
                print("\nTop Improvements Required:")
                for i, imp in enumerate(report.get('top_improvements', []), 1):
                    print(f"  {i}. {imp}")
        else:
            print("No final report generated by Crew.")
            
        print("="*50 + "\n")
        
        # Save output
        serialized_results = {}
        for k, v in results.items():
            if hasattr(v, "model_dump_json"):
                serialized_results[k] = json.loads(v.model_dump_json())
            elif hasattr(v, "__dict__"):
                serialized_results[k] = v.__dict__
            else:
                serialized_results[k] = v
                
        with open(args.output, "w", encoding="utf-8") as out_f:
            json.dump(serialized_results, out_f, indent=2, ensure_ascii=False)
        print(f"Full structured results saved to: {args.output}")
        
    except Exception as e:
        print(f"Execution failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
